export const supaUrl = 'https://nseryvxcevnapyixolpw.supabase.co'

export const anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZXJ5dnhjZXZuYXB5aXhvbHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMjcxMTcsImV4cCI6MjA1NDcwMzExN30.vKiGcGwnpKowTcRljDR0xPHhwkpjbfRgyQ8h_n-93Dg'